name: Auto-Curate Workflow

on:
  workflow_dispatch:

jobs:
  curate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say hi from Jelly 🧠
        run: echo "Let’s curate some knowledge!"
