name: Auto-Curate Workflow

on:
  workflow_dispatch:

jobs:
  curate:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger local n8n Jelly AI Curator 🧠
        run: |
          curl -X POST https://315e2c9650cf.ngrok-free.app/webhook/reddit-curator \
            -H "Content-Type: application/json" \
            -d '{"trigger": "github-action"}'

